// H2 PC GSC
// Decompiled by https://github.com/xensik/gsc-tool

main()
{
    level._ID1426["zpu_muzzle"] = loadfx( "fx/muzzleflashes/zpu_flash_gulag" );
    level._ID1426["dynamic_godray"] = loadfx( "fx/misc/dynamic_godray" );
    level._ID1426["lensflare_floodlight_on"] = loadfx( "vfx/lights/lensflare_floodlight_on" );
    level._ID1426["spotlight_cone_haze"] = loadfx( "fx/lights/spotlight_cone_haze" );
    level._ID1426["spotlight_cone_haze_nobeam"] = loadfx( "fx/lights/spotlight_cone_haze_nobeam" );
    level._ID1426["amb_steam_crawling"] = loadfx( "vfx/steam/amb_steam_crawling" );
    level._ID1426["amb_light_dust"] = loadfx( "vfx/dust/amb_light_dust" );
    level._ID1426["firelp_barrel_pm"] = loadfx( "fx/fire/firelp_barrel_pm" );
    level._ID1426["dust_falling_ceiling_short"] = loadfx( "fx/dust/dust_falling_ceiling_short" );
    level._ID1426["dust_falling_ceiling_02"] = loadfx( "fx/dust/dust_falling_ceiling_02" );
    level._ID1426["insects_roach_scatter_straight_runner"] = loadfx( "vfx/animal/insects_roach_scatter_straight_runner" );
    level._ID1426["insects_roach_scatter_radial_runner"] = loadfx( "vfx/animal/insects_roach_scatter_radial_runner" );
    level._ID1426["insects_roach_flock_slow_crawl_runner"] = loadfx( "vfx/animal/insects_roach_flock_slow_crawl_runner" );
    level._ID1426["roach_single_rt_turn"] = loadfx( "vfx/animal/roach_single_rt_turn" );
    level._ID1426["roach_flock_scatter_runner"] = loadfx( "vfx/map/mp_clowntown/roach_flock_scatter_runner" );
    level._ID1426["fog_ground_200"] = loadfx( "vfx/fog/fog_ground_200_gulag" );
    level._ID1426["fog_ground_corridor"] = loadfx( "vfx/fog/fog_ground_corridor_gulag" );
    level._ID1426["fog_shower_high"] = loadfx( "vfx/fog/fog_ground_high_gulag" );
    level._ID1426["dust_falling_ceiling_gray_runner"] = loadfx( "fx/dust/dust_falling_ceiling_gray_runner" );
    level._ID1426["bombardment_dust_falling_runner"] = loadfx( "vfx/dust/bombardment_dust_falling_runner" );
    level._ID1426["dust_motes"] = loadfx( "fx/dust/dust_motes" );
    level._ID1426["amb_dust_int"] = loadfx( "fx/dust/amb_dust_int" );
    level._ID1426["dust_ambient_interior_big"] = loadfx( "vfx/smoke/dust_ambient_interior_big" );
    level._ID1426["distorsion_smoke"] = loadfx( "fx/distortion/heat_distorsion_smoke" );
    level._ID1426["distorsion_warm_heat"] = loadfx( "vfx/distortion/distortion_warm_heat" );
    level._ID1426["distorsion_motor_heat"] = loadfx( "vfx/distortion/motor_heat_distorsion_gulag" );
    level._ID1426["goldenpath_door"] = loadfx( "vfx/unique/godray_path_door_gulag" );
    level._ID1426["godray_cathedral"] = loadfx( "vfx/lights/godray_cathedral_gulag" );
    level._ID1426["godray_cathedral_sml"] = loadfx( "vfx/lights/godray_cathedral_gulag_sml" );
    level._ID1426["godray_cathedral_lrg"] = loadfx( "vfx/lights/godray_cathedral_gulag_lrg" );
    level._ID1426["drips_slow"] = loadfx( "vfx/rain/drips_slow_gulag" );
    level._ID1426["drips_slow_shower"] = loadfx( "vfx/rain/drips_slow_shower_gulag" );
    level._ID1426["drips_single"] = loadfx( "vfx/rain/drips_slow_single" );
    level._ID1426["steam_pipe_leak_interior_loop_sml"] = loadfx( "vfx/steam/steam_pipe_leak_interior_loop_sml" );
    level._ID1426["sparks"] = loadfx( "vfx/sparks/spark_idle" );
    level._ID1426["sparks_single"] = loadfx( "vfx/sparks/spark_idle_nospark" );
    level._ID1426["bullet_spark"] = loadfx( "fx/impacts/large_metalhit_1" );
    level._ID1426["steam_pipe_leak_interior_loop_med"] = loadfx( "vfx/steam/steam_pipe_leak_interior_loop_med" );
    level._ID1426["steam_pipe_leak_interior_loop_lrg"] = loadfx( "vfx/steam/steam_pipe_leak_interior_loop_lrg" );
    level._ID1426["water_pipe_leak_interior_loop"] = loadfx( "vfx/water/water_pipe_leak_interior_loop" );
    level._ID1426["grid_steam_single"] = loadfx( "fx/smoke/grid_steam_single" );
    level._ID1426["steam_building_lingering"] = loadfx( "fx/steam/steam_building_lingering" );
    level._ID1426["amb_steam_crawling_02"] = loadfx( "vfx/steam/amb_steam_crawling_02" );
    level._ID1426["static_steam_vent_small"] = loadfx( "vfx/steam/static_steam_vent_small" );
    level._ID1426["steam_square_manhole"] = loadfx( "vfx/steam/steam_square_manhole" );
    level._ID1426["snow_window"] = loadfx( "vfx/snow/snow_window_gulag" );
    level._ID1426["snow_window_cathedral"] = loadfx( "vfx/snow/snow_window_cathedral_gulag" );
    level._ID1426["heli_landing_snow"] = loadfx( "vfx/map/gulag/heli_landing_staged_gulag" );
    level._ID1426["wfall_tower"] = loadfx( "vfx/water/falling_water_tower" );
    level._ID1426["wfall_tower_sml"] = loadfx( "vfx/water/falling_water_tower_sml" );
    level._ID1426["wfall_tower_lrg"] = loadfx( "vfx/water/falling_water_tower_lrg" );
    level._ID1426["wfall_splash"] = loadfx( "vfx/water/waterfall_splash_gulag" );
    level._ID1426["wfall_splash_sml"] = loadfx( "vfx/water/waterfall_splash_sml_gulag" );
    level._ID1426["wfall_steam"] = loadfx( "vfx/water/waterfall_steam_gulag" );
    level._ID1426["wfall_steam_top"] = loadfx( "vfx/water/waterfall_steam_top_gulag" );
    level._ID1426["wfall_floor_current"] = loadfx( "vfx/water/waterfall_floor_current" );
    level._ID1426["breach_price"] = loadfx( "fx/explosions/gulag_price_breach" );
    level._ID1426["water_stop"] = loadfx( "fx/misc/parabolic_water_stand" );
    level._ID1426["water_movement"] = loadfx( "fx/misc/parabolic_water_movement" );
    level._ID1426["sparks_e_sound"] = loadfx( "fx/explosions/sparks_e_sound" );
    level._ID1426["welding_small_extended"] = loadfx( "fx/misc/welding_small_extended" );
    level._ID1426["grenade_wood"] = loadfx( "fx/explosions/grenadeExp_wood" );
    level._ID1426["headshot"] = loadfx( "fx/impacts/flesh_hit_head_fatal_exit" );
    level._ID1426["hallway_collapsing"] = loadfx( "fx/misc/hallway_collapsing" );
    level._ID1426["hallway_collapsing_big"] = loadfx( "fx/misc/hallway_collapsing_big" );
    level._ID1426["hallway_collapsing_huge"] = loadfx( "fx/misc/hallway_collapsing_huge" );
    level._ID1426["hallway_collapsing_chase"] = loadfx( "fx/misc/hallway_collapsing_chase" );
    level._ID1426["hallway_collapsing_cavein"] = loadfx( "fx/misc/hallway_collapsing_cavein" );
    level._ID1426["hallway_collapsing_cavein_short"] = loadfx( "fx/misc/hallway_collapsing_cavein_short" );
    level._ID1426["hallway_collapsing_burst"] = loadfx( "fx/misc/hallway_collapsing_burst" );
    level._ID1426["hallway_collapsing_burst_no_linger"] = loadfx( "fx/misc/hallway_collapsing_burst_no_linger" );
    level._ID1426["hallway_collapsing_major"] = loadfx( "fx/misc/hallway_collapsing_major" );
    level._ID1426["hallway_collapsing_major_norocks"] = loadfx( "fx/misc/hallway_collapsing_major_norocks" );
    level._ID1426["hallway_collapse_smoke_runner"] = loadfx( "fx/smoke/hallway_collapse_smoke_runner" );
    level._ID1426["hallway_collapse_smoke_runner_short"] = loadfx( "fx/smoke/hallway_collapse_smoke_runner_short" );
    level._ID1426["hallway_cavein_smoke_runner_no_linger"] = loadfx( "fx/smoke/hallway_cavein_smoke_runner_no_linger" );
    level._ID1426["hallway_collapse_smoke_swirl_runner"] = loadfx( "fx/smoke/hallway_collapse_smoke_swirl_runner" );
    level._ID1426["hallway_collapse_smoke_swirl_runner_2"] = loadfx( "fx/smoke/hallway_collapse_smoke_swirl_runner_2" );
    level._ID1426["hallway_collapse_ceiling_smoke"] = loadfx( "fx/smoke/hallway_collapse_ceiling_smoke" );
    level._ID1426["hallway_cavein_smoke_runner"] = loadfx( "fx/smoke/hallway_cavein_smoke_runner" );
    level._ID1426["footstep_snow"] = loadfx( "fx/impacts/footstep_snow" );
    level._ID1426["footstep_snow_small"] = loadfx( "fx/impacts/footstep_snow_small" );
    level._ID1426["ceiling_collapse_dirt1"] = loadfx( "fx/dust/ceiling_collapse_dirt1" );
    level._ID1426["ceiling_collapse_dirt1_decal"] = loadfx( "fx/dust/ceiling_collapse_dirt1_decal" );
    level._ID1426["ceiling_rock_break"] = loadfx( "fx/misc/ceiling_rock_break" );
    level._ID1426["ceiling_rock_break_decal"] = loadfx( "fx/misc/ceiling_rock_break_decal" );
    level._ID1426["ceiling_rock_break_grow"] = loadfx( "fx/misc/ceiling_rock_break_grow" );
    level._ID1426["rock_falling_large"] = loadfx( "fx/misc/rock_falling_large" );
    level._ID1426["glass_falling"] = loadfx( "fx/misc/glass_falling" );
    level._ID1426["falling_debris_ring"] = loadfx( "fx/misc/falling_debris_ring" );
    level._ID1426["trash_paper_dropping"] = loadfx( "fx/misc/trash_paper_dropping" );
    level._ID1426["waterfall_drainage"] = loadfx( "fx/water/waterfall_drainage" );
    level._ID1426["waterfall_drainage_distortion"] = loadfx( "fx/water/waterfall_drainage_distortion" );
    level._ID1426["waterfall_drainage_splash"] = loadfx( "fx/water/waterfall_drainage_splash" );
    level._ID1426["waterfall_drainage_splash_falling"] = loadfx( "fx/water/waterfall_drainage_splash_falling" );
    level._ID1426["gulag_cafe_spotlight"] = loadfx( "fx/misc/gulag_cafe_spotlight" );
    level._ID1426["firelp_large_pm"] = loadfx( "fx/fire/firelp_large_pm" );
    level._ID1426["firelp_med_pm"] = loadfx( "fx/fire/firelp_med_pm" );
    level._ID1426["flare_start_gulag"] = loadfx( "fx/misc/flare_start_gulag" );
    level._ID1426["flare_gulag"] = loadfx( "fx/misc/flare_gulag" );
    level._ID1426["water_slide"] = loadfx( "fx/water/water_slide" );
    level._ID1426["water_slide_splash"] = loadfx( "fx/water/water_slide_splash" );
    level._ID1426["water_slide_splash_player"] = loadfx( "fx/water/water_slide_splash_player" );
    level._ID1426["water_slide_start"] = loadfx( "fx/water/water_slide_start" );
    level._ID1426["water_slide_player"] = loadfx( "fx/water/water_slide_player" );
    level._ID1426["falling_water_trickle"] = loadfx( "fx/water/falling_water_trickle" );
    level._ID1426["wall_explosion_2"] = loadfx( "fx/explosions/wall_explosion_2" );
    level._ID1426["wall_explosion_2_short"] = loadfx( "fx/explosions/wall_explosion_2_short" );
    level._ID1426["wall_explosion_2_short_nosmoke"] = loadfx( "fx/explosions/wall_explosion_2_short_nosmoke" );
    level._ID1426["building_explosion_mega_gulag"] = loadfx( "fx/explosions/building_explosion_mega_gulag" );
    level._ID1426["fireball_gulag"] = loadfx( "fx/explosions/fireball_gulag" );
    level._ID1426["player_cavein"] = loadfx( "fx/smoke/player_cavein" );
    level._ID1426["debri_explosion"] = loadfx( "fx/explosions/debri_explosion" );
    level._ID1426["falling_debrigulag_evac"] = loadfx( "fx/misc/falling_debris_gulag_evac" );
    level._ID1426["dlight_blue"] = loadfx( "fx/misc/dlight_blue" );
    level._ID1426["dlight_blue_flicker"] = loadfx( "fx/misc/dlight_blue_flicker" );
    level._ID1426["dlight_red"] = loadfx( "fx/misc/dlight_red" );
    level._ID1426["flesh_hit"] = loadfx( "fx/impacts/flesh_hit_body_fatal_exit" );
    level._ID1426["spotlight_hanged"] = loadfx( "vfx/lights/light_spotlight_long_gulag" );
    level._ID1426["spotlight_hanged_flicker"] = loadfx( "vfx/lights/light_spotlight_long_gulag_flicker" );
    level._ID1426["spotlight_hanged_soft"] = loadfx( "vfx/lights/light_spotlight_soft_gulag" );
    level._ID1426["minigun_shell_eject"] = loadfx( "fx/shellejects/20mm_mp" );
    level._ID1426["f15_missile"] = loadfx( "fx/smoke/smoke_geotrail_sidewinder" );
    level._ID1426["castletower_2_collapse_gulag"] = loadfx( "vfx/smoke/castletower_2_collapse_gulag" );
    level._ID1426["missile_brackets"] = loadfx( "fx/misc/missile_brackets" );
    level._ID1426["javelin_ignition"] = loadfx( "fx/misc/javelin_ignition_gulag" );
    level._ID1426["jet_afterburner_ignite"] = loadfx( "fx/fire/jet_afterburner_ignite" );
    level._ID1426["javelin_trail"] = loadfx( "fx/smoke/smoke_geotrail_javelin_gulag_flyin" );
    level._ID1426["tracer_incoming"] = loadfx( "fx/misc/tracer_incoming" );
    level._ID1426["smoke_swirl_runner_dual"] = loadfx( "fx/smoke/smoke_swirl_runner_dual" );
    level._ID1426["missile_explosion"] = loadfx( "fx/explosions/vehicle_explosion_bmp" );
    level._ID1426["f15_smoke"] = loadfx( "fx/smoke/smoke_trail_black_jet" );
    level._ID1426["building_explosion_gulag"] = loadfx( "fx/explosions/building_explosion_gulag" );
    level._ID1426["building_explosion_gulag_blowback"] = loadfx( "fx/explosions/building_explosion_gulag_blowback" );
    level._ID1426["building_explosion_huge_gulag"] = loadfx( "fx/explosions/building_explosion_huge_gulag" );
    level._ID1426["building_explosion_metal_gulag"] = loadfx( "fx/explosions/building_explosion_metal_gulag" );
    level._ID1426["bhd_dirt"] = loadfx( "fx/impacts/bhd_dirt" );
    level._ID1426["smoke_pushed"] = loadfx( "fx/smoke/smoke_pushed" );
    level._ID1426["jet_crash"] = loadfx( "fx/explosions/jet_crash" );
    level._ID1426["jet_crash_bounce"] = loadfx( "fx/explosions/jet_crash_bounce" );
    level._ID1426["jet_crash_smoke_blow_1"] = loadfx( "fx/explosions/jet_crash_smoke_blow_1" );
    level._ID1426["jet_crash_smoke_blow_2"] = loadfx( "fx/explosions/jet_crash_smoke_blow_2" );
    level._ID1426["jet_crash_smoke_fill"] = loadfx( "fx/explosions/jet_crash_smoke_fill" );
    level._ID1426["thin_black_smoke_L"] = loadfx( "fx/smoke/thin_black_smoke_l_ctower_gulag" );
    level._ID1426["thick_black_smoke_L"] = loadfx( "fx/smoke/thick_black_smoke_L" );
    level._ID1426["missile_trail"] = loadfx( "fx/smoke/gulag_missile_trail" );
    level._ID1426["powerline_runner_10sec_line"] = loadfx( "fx/explosions/powerline_runner_10sec_line" );
    level._ID1426["amb_ash"] = loadfx( "fx/smoke/amb_ash" );
    level._ID1426["amb_smoke_blend"] = loadfx( "fx/smoke/amb_smoke_blend" );
    level._ID1426["battlefield_smokebank_bog_a"] = loadfx( "fx/smoke/battlefield_smokebank_bog_a" );
    level._ID1426["amb_smoke_add"] = loadfx( "fx/smoke/amb_smoke_add" );
    level._ID1426["battlefield_smokebank_S"] = loadfx( "fx/smoke/battlefield_smokebank_S" );
    level._ID1426["insect_trail_runner"] = loadfx( "fx/misc/insect_trail_runner" );
    level._ID1426["moth_runner"] = loadfx( "fx/misc/moth_runner" );
    level._ID1426["dust_wind_slow_broadcast"] = loadfx( "fx/dust/dust_wind_slow_broadcast" );
    level._ID1426["fog_bog_a"] = loadfx( "fx/weather/fog_bog_a" );
    level._ID1426["dust_ceiling_ash_small"] = loadfx( "fx/dust/dust_ceiling_ash_small" );
    level._ID1426["hallway_smoke_light"] = loadfx( "fx/smoke/hallway_smoke_light_gulag" );
    level._ID1426["hawk"] = loadfx( "fx/weather/hawk" );
    level._ID1426["dust_wind_slow_loop_gulag"] = loadfx( "fx/dust/dust_wind_slow_loop_gulag" );
    level._ID1426["firelp_med_pm"] = loadfx( "fx/fire/firelp_med_pm" );
    level._ID1426["firelp_small_pm"] = loadfx( "fx/fire/firelp_small_pm" );
    level._ID1426["fire_falling_runner_point"] = loadfx( "fx/fire/fire_falling_runner_point" );
    level._ID1426["car_fire_ground_sml_gulag"] = loadfx( "fx/fire/car_fire_ground_sml_gulag" );
    level._ID1426["car_fire_body_gulag"] = loadfx( "fx/fire/car_fire_body_gulag" );
    level._ID1426["car_fire_body_landslide_gulag"] = loadfx( "fx/fire/car_fire_body_landslide_gulag" );
    level._ID1426["car_fire_motor_gulag"] = loadfx( "fx/fire/car_fire_motor_gulag" );
    level._ID1426["heli_crashed_courtyard_gulag"] = loadfx( "fx/fire/heli_crashed_courtyard_gulag" );
    level._ID1426["snow_blowoff_gulag_runner"] = loadfx( "fx/snow/snow_blowoff_gulag_runner" );
    level._ID1426["snow_blow_gulag"] = loadfx( "vfx/snow/snow_blow_gulag" );
    level._ID1426["snow_spray_detail_runner_gulag"] = loadfx( "fx/snow/snow_spray_detail_runner_gulag" );
    level._ID1426["fire_drip_gulag"] = loadfx( "vfx/fire/fire_drip_gulag" );
    level._ID1426["ambient_snowing_gulag"] = loadfx( "vfx/snow/ambient_snowing_gulag" );
    level._ID1426["fire_crawl_gulag"] = loadfx( "vfx/fire/fire_crawl_gulag" );
    level._ID1426["fire_building_airlift"] = loadfx( "vfx/fire/fire_building_airlift" );
    level._ID1426["fire_building_gulag"] = loadfx( "vfx/fire/fire_building_gulag" );
    level._ID1426["fire_small_gulag"] = loadfx( "vfx/fire/fire_small_gulag" );
    level._ID1426["cloud_bank_far_gulag"] = loadfx( "fx/weather/cloud_bank_far_gulag" );
    level._ID1426["cloud_bank_gulag"] = loadfx( "fx/weather/cloud_bank_gulag" );
    level._ID1426["cloud_bank_gulag_z_feather"] = loadfx( "fx/weather/cloud_bank_gulag_z_feather" );
    level._ID1426["cloud_bank_thick_gulag"] = loadfx( "fx/weather/cloud_bank_thick_gulag" );
    level._ID1426["cloud_bank_opaque_1_gulag"] = loadfx( "fx/weather/cloud_bank_opaque_1_gulag" );
    level._ID1426["cloud_bank_opaque_2_gulag"] = loadfx( "fx/weather/cloud_bank_opaque_2_gulag" );
    level._ID1426["cloud_bank_opaque_oriented_gulag"] = loadfx( "fx/weather/cloud_bank_opaque_oriented_gulag" );
    level._ID1426["cloud_bank_cloud_filler_gulag"] = loadfx( "fx/weather/cloud_bank_cloud_filler_gulag" );
    level._ID1426["cloud_bank_cloud_filler_tight_gulag"] = loadfx( "fx/weather/cloud_bank_cloud_filler_tight_gulag" );
    level._ID1426["cloud_bank_cloud_filler_tight_hazy_gulag"] = loadfx( "fx/weather/cloud_bank_cloud_filler_tight_hazy_gulag" );
    level._ID1426["cloud_bank_cloud_filler_light_gulag"] = loadfx( "fx/weather/cloud_bank_cloud_filler_light_gulag" );
    level._ID1426["gulag_clouds"] = loadfx( "fx/weather/gulag_clouds" );
    level._ID1426["rat_flock_straight"] = loadfx( "vfx/animal/rat_flock_straight" );
    level._ID1426["rat_flock_straight_lp"] = loadfx( "vfx/animal/rat_flock_straight_lp" );
    level._ID1426["rat_bleed"] = loadfx( "vfx/blood/dlc_blood_splash_sm" );
    level._ID1426["bombardment_dust_falling_runner"] = loadfx( "vfx/dust/bombardment_dust_falling_runner" );
    level._ID1426["big_window_fire"] = loadfx( "vfx/fire/big_window_fire" );
    level._ID1426["amb_smoke_dark"] = loadfx( "vfx/map/airlift/amb_smoke_dark" );
    level._ID1426["window_glass_explosion"] = loadfx( "vfx/glass/window_glass_explosion" );
    level._ID1426["emergency_light_gulag"] = loadfx( "vfx/lights/emergency_light_gulag" );
    level._ID1426["blue_spotlight_cone_haze"] = loadfx( "fx/lights/blue_spotlight_cone_haze" );
    level._ID1426["fx_sunflare_gulag"] = loadfx( "vfx/lensflare/fx_sunflare_gulag" );
    level._ID1426["small_wide_fire_gulag"] = loadfx( "vfx/fire/small_wide_fire_gulag" );
    level._ID1426["snow_window_slow_gulag"] = loadfx( "vfx/snow/snow_window_slow_gulag" );
    level._ID1426["small_dark_smoke_gulag"] = loadfx( "vfx/smoke/small_dark_smoke_gulag" );
    level._ID1426["ash_column_falling_gulag"] = loadfx( "fx/misc/ash_column_falling_gulag" );
    level._ID1426["thin_black_smoke_l_gulag"] = loadfx( "fx/smoke/thin_black_smoke_l_gulag" );
    level._ID1426["tire_fire_gulag"] = loadfx( "fx/fire/tire_fire_gulag" );
    level._ID1426["snow_spray_single_detail_lp_gulag"] = loadfx( "fx/snow/snow_spray_single_detail_lp_gulag" );
    level._ID1426["steam_square_manhole_ext"] = loadfx( "vfx/steam/steam_square_manhole_ext" );
    level._ID1426["steam_building_side_vent_2_gulag"] = loadfx( "vfx/steam/steam_building_side_vent_2_gulag" );
    level._ID1426["building_explosion_aerial_gulag"] = loadfx( "fx/explosions/building_explosion_aerial_gulag" );
    level._ID1426["tower_light_blue_steady"] = loadfx( "fx/misc/tower_light_blue_steady" );
    level._ID1426["bhd_wood_impact"] = loadfx( "fx/impacts/bhd_wood_impact" );
    level._ID1426["bhd_sand_impact"] = loadfx( "fx/impacts/bhd_sand_impact" );
    level._ID1426["bhd_minigun_impact_bomb"] = loadfx( "vfx/weaponimpact/bhd_minigun_impact_bomb" );
    level._ID1426["amb_snow_heli_hack"] = loadfx( "fx/weather/amb_snow_heli_hack" );
    level._ID1426["jail_spotlight_gulag"] = loadfx( "fx/misc/jail_spotlight_gulag" );
    level._ID1426["steam_sm_vent_gulag"] = loadfx( "vfx/steam/steam_sm_vent_gulag" );
    level._ID1426["steam_building_side_vent_push_gulag"] = loadfx( "vfx/steam/steam_building_side_vent_push_gulag" );
    level._ID1426["steam_sm_vent_side_gulag"] = loadfx( "vfx/steam/steam_sm_vent_side_gulag" );
    level._ID1426["amb_dust_int_gulag_cell"] = loadfx( "fx/dust/amb_dust_int_gulag_cell" );
    level._ID1426["fog_dark_cell_gulag"] = loadfx( "fx/weather/fog_dark_cell_gulag" );
    level._ID1426["falling_water_tower_cellblock1_lrg"] = loadfx( "vfx/water/falling_water_tower_cellblock1_lrg" );
    level._ID1426["waterfall_drainage_splash_gulag"] = loadfx( "fx/water/waterfall_drainage_splash_gulag" );
    level._ID1426["waterfall_floor_current_gulag_sewer"] = loadfx( "vfx/water/waterfall_floor_current_gulag_sewer" );
    level._ID1426["light_rays_gulag_sewer_waterfall"] = loadfx( "vfx/lights/light_rays_gulag_sewer_waterfall" );
    level._ID1426["dripping_water_gulag"] = loadfx( "vfx/water/dripping_water_gulag" );
    level._ID1426["godray_path_sewer_gulag"] = loadfx( "vfx/unique/godray_path_sewer_gulag" );
    level._ID1426["yellow_lensflare_floodlight_on"] = loadfx( "vfx/lights/yellow_lensflare_floodlight_on" );
    level._ID1426["pipe_water_flow_gulag"] = loadfx( "fx/water/pipe_water_flow_gulag" );
    level._ID1426["small_splash_gulag_sewer"] = loadfx( "fx/water/small_splash_gulag_sewer" );
    level._ID1426["water_splash_small_gulag"] = loadfx( "vfx/water/water_splash_small_gulag" );
    level._ID1426["waterfall_splash_base_sewer_gulag"] = loadfx( "vfx/water/waterfall_splash_base_sewer_gulag" );
    level._ID1426["fog_ground_200_gulag_sewer"] = loadfx( "vfx/fog/fog_ground_200_gulag_sewer" );
    level._ID1426["water_pipe_leak_interior_loop_sewer_gulag"] = loadfx( "vfx/water/water_pipe_leak_interior_loop_sewer_gulag" );
    level._ID1426["hallway_collapsing_burst_gulag"] = loadfx( "fx/misc/hallway_collapsing_burst_gulag" );
    level._ID1426["snow_window_lrg_gulag"] = loadfx( "vfx/snow/snow_window_lrg_gulag" );
    level._ID1426["hallway_collapsing_burst_gulag_runner"] = loadfx( "fx/misc/hallway_collapsing_burst_gulag_runner" );
    level._ID1426["hallway_ground_black_smoke"] = loadfx( "vfx/map/captured/hallway_ground_black_smoke" );
    level._ID1426["radio_tower_falling_snow_gulag"] = loadfx( "fx/snow/radio_tower_falling_snow_gulag" );
    level._ID1426["hallway_collapsing_huge_block"] = loadfx( "fx/misc/hallway_collapsing_huge_block" );
    level._ID1426["hallway_smoke_escape"] = loadfx( "vfx/smoke/hallway_smoke_escape" );
    level._ID1426["fire_falling_runner_point_1"] = loadfx( "vfx/fire/fire_falling_runner_point" );
    level._ID1426["steam_broken_pipe"] = loadfx( "vfx/test/hms_vfx_bj/steam_broken_pipe" );
    level._ID1426["paper_blowing_burnt_gulag"] = loadfx( "fx/misc/paper_blowing_burnt_gulag" );
    level._ID1426["fire_building_gulag_smlfog"] = loadfx( "vfx/fire/fire_building_gulag_smlfog" );
    level._ID1426["firelp_small_pm_gulag"] = loadfx( "fx/fire/firelp_small_pm_gulag" );
    level._ID1426["wall_explosion_2_short_gulag"] = loadfx( "fx/explosions/wall_explosion_2_short_gulag" );
    level._ID1426["wall_explosion_2_med"] = loadfx( "fx/explosions/wall_explosion_2_med" );
    level._ID1426["hole_godray_gulag"] = loadfx( "vfx/snow/hole_godray_gulag" );
    level._ID1426["rockslide_gulag"] = loadfx( "vfx/map/gulag/rockslide_gulag" );
    level._ID1426["rockslide_splash_gulag"] = loadfx( "vfx/map/gulag/rockslide_splash_gulag" );
    level._ID1426["rockslide_splash_gulag_runner"] = loadfx( "vfx/map/gulag/rockslide_splash_gulag_runner" );
    level._ID1426["radio_tower_fall_light_flicker"] = loadfx( "fx/misc/radio_tower_fall_light_flicker" );
    level._ID1426["radio_tower_fall_sparks_runner"] = loadfx( "vfx/sparks/radio_tower_fall_sparks_runner" );
    level._ID1426["h2_ash_embers_heavy_lg"] = loadfx( "vfx/ash/h2_ash_embers_heavy_lg" );
    level._ID1426["aircraft_omnilight_cockpit_gulag"] = loadfx( "fx/misc/aircraft_omnilight_cockpit_gulag" );
    level._ID1426["aircraft_spotlight_cockpit_gulag"] = loadfx( "fx/misc/aircraft_spotlight_cockpit_gulag" );
    level._ID1426["aircraft_omnilight_cockpit_gulag_out"] = loadfx( "fx/misc/aircraft_omnilight_cockpit_gulag_out" );
    level._ID1426["aircraft_spotlight_cockpit_gulag_out"] = loadfx( "fx/misc/aircraft_spotlight_cockpit_gulag_out" );
    level._ID1426["aircraft_spotlight_cockpit_gulag_2"] = loadfx( "fx/misc/aircraft_spotlight_cockpit_gulag_2" );
    level._ID1426["aircraft_spotlight_cockpit_gulag_2_out"] = loadfx( "fx/misc/aircraft_spotlight_cockpit_gulag_2_out" );
    level._ID1426["wall_explosion_1_med"] = loadfx( "fx/explosions/wall_explosion_1_med" );
    level._ID1426["hallway_collapsing_loop"] = loadfx( "fx/misc/hallway_collapsing_loop" );
    level._ID1426["jet_water"] = loadfx( "fx/treadfx/jet_water" );
    level._ID1426["ground_linger_dark_smk"] = loadfx( "vfx/smoke/ground_linger_dark_smk" );
    level._ID1426["sewer_water_gulag"] = loadfx( "fx/water/sewer_water_gulag" );
    level._ID1426["water_splash_light_sewer"] = loadfx( "vfx/map/mp_climate/water_splash_light_sewer" );
    level._ID1426["dirty_foam_fast_gulag_sewer"] = loadfx( "vfx/water/dirty_foam_fast_gulag_sewer" );
    level._ID1426["water_slide_end_gulag_sewer"] = loadfx( "fx/water/water_slide_end_gulag_sewer" );
    level._ID1426["radio_tower_red_static_glow"] = loadfx( "fx/misc/radio_tower_red_static_glow" );
    level._ID1426["bhd_wood_beam_explosion"] = loadfx( "fx/explosions/bhd_wood_beam_explosion" );
    level._ID1426["bhd_minigun_impact_bomb_02"] = loadfx( "vfx/weaponimpact/bhd_minigun_impact_bomb_02" );
    level._ID1426["traverse_watersplash_gulag"] = loadfx( "vfx/water/traverse_watersplash_gulag" );
    level._ID1426["rockslide_big_splash_gulag"] = loadfx( "vfx/map/gulag/rockslide_big_splash_gulag" );
    level._ID1426["large_metalhit_gulag"] = loadfx( "vfx/weaponimpact/large_metalhit_gulag" );
    level._ID1426["smoke_ambiant_tunnel"] = loadfx( "vfx/smoke/smoke_ambiant_tunnel" );
    level._ID1426["metalhit_tag_gulag"] = loadfx( "vfx/weaponimpact/metalhit_tag_gulag" );
    level._ID1426["large_metalhit_gulag"] = loadfx( "vfx/weaponimpact/large_metalhit_gulag" );
    level._ID1426["heli_water_loop"] = loadfx( "fx/treadfx/heli_water_loop" );
    level._ID1426["heli_snow_default_landing"] = loadfx( "fx/treadfx/heli_snow_default_landing" );
    level._ID1426["battlefield_smk_directional_white_gulag"] = loadfx( "fx/smoke/battlefield_smk_directional_white_gulag" );
    level._ID1426["large_explosion_gulag"] = loadfx( "vfx/explosion/large_explosion_gulag" );
    level._ID1426["no_fx"] = loadfx( "vfx/unique/no_fx" );
    level._ID1426["ambient_cloud_fog_area_local_gulag"] = loadfx( "vfx/map/airlift/ambient_cloud_fog_area_local_gulag" );
    level._ID1426["fire_building_large_gulag"] = loadfx( "vfx/fire/fire_building_large_gulag" );
    level._ID1426["firelp_small_surface_runner_gulag"] = loadfx( "fx/fire/firelp_small_surface_runner_gulag" );
    level._ID1426["greenlight_charge_breach_gulag"] = loadfx( "vfx/lights/greenlight_charge_breach_gulag" );
    level._ID1426["redlight_charge_breach_gulag"] = loadfx( "vfx/lights/redlight_charge_breach_gulag" );
    level._ID1426["sparks_exp_gulag"] = loadfx( "vfx/sparks/sparks_exp_gulag" );
    level._ID1426["battlefield_smoke_l_fast"] = loadfx( "vfx/smoke/dlc/battlefield_smoke_l_fast" );
    level._ID1426["jail_spotlight_gulag_static"] = loadfx( "fx/misc/jail_spotlight_gulag_static" );
    level._ID1426["water_cam_drop_zone"] = loadfx( "vfx/water/water_cam_drop_zone" );
    level._ID1426["fog_vista_emiss_gulag"] = loadfx( "vfx/cloud/fog_vista_emiss_gulag" );
    level._ID1426["building_explosion_smoke_wall"] = loadfx( "fx/smoke/building_explosion_smoke_wall" );
    level._ID1426["light_utility_sewer_gulag"] = loadfx( "vfx/lights/light_utility_sewer_gulag" );
    level._ID1426["building_explosion_smoke_wall02"] = loadfx( "fx/smoke/building_explosion_smoke_wall02" );
    level._ID1426["entrance_lighthaze_gulag"] = loadfx( "fx/misc/entrance_lighthaze_gulag" );
    level._ID1426["cellblock_lighthaze_gulag"] = loadfx( "fx/misc/cellblock_lighthaze_gulag" );
    level._ID1426["propane_large_exp_h2_gulag"] = loadfx( "fx/explosions/propane_large_exp_h2_gulag" );
    level._ID1426["icicle_tall_des"] = loadfx( "fx/props/icicle_tall_des" );
    level._ID1426["icicle_mid_des"] = loadfx( "fx/props/icicle_mid_des" );
    level._ID1426["heli_crashed_door_courtyard_gulag"] = loadfx( "fx/fire/heli_crashed_door_courtyard_gulag" );
    level._ID1426["yellow_lensflare_big_floodlight_on"] = loadfx( "vfx/lights/yellow_lensflare_big_floodlight_on" );
    _ID42508::_ID3619();

    if ( !isdefined( level.script ) )
        level.script = tolower( getdvar( "mapname" ) );

    if ( !getdvarint( "r_reflectionProbeGenerate" ) )
        _ID44141::main();

    thread _ID38735();
    _ID45832();
    _ID49799();
    _ID42407::_ID1885( "boat_artillery", 0.35, 0.75, 4500 );
    _ID42407::_ID1885( "ceiling_collapse", 0.4, 4, 4500 );
    animscripts\utility::_ID32631( "snow", loadfx( "fx/impacts/footstep_snow" ) );
    animscripts\utility::_ID32632( "snow", loadfx( "fx/impacts/footstep_snow_small" ) );
}

_ID53311()
{
    self endon( "death" );
    var_0 = _ID42237::_ID16299( "f15_smoke" );

    for (;;)
    {
        playfxontag( var_0, self, "tag_engine_left" );
        stopfxontag( var_0, self, "tag_engine_right" );
        wait 0.01;
    }
}

_ID38735()
{
    var_0 = "fx/treadfx/heli_snow_default";
    var_1 = "fx/treadfx/heli_water_loop";
    var_2 = "vfx/unique/no_fx";
    var_3 = [ "script_vehicle_littlebird_armed", "script_vehicle_littlebird_bench", "script_vehicle_littlebird_bench_allylanding_1", "script_vehicle_littlebird_bench_allylanding_2" ];

    foreach ( var_5 in var_3 )
    {
        _ID42400::_ID33619( var_5, "brick", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "bark", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "carpet", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "cloth", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "concrete", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "dirt", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "flesh", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "foliage", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "glass", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "grass", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "gravel", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "ice", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "metal", undefined, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "mud", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "paper", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "plaster", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "rock", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "sand", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "snow", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "slush", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "water", var_1, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "water_waist", var_1, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "wood", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "asphalt", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "ceramic", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "plastic", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "rubber", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "cushion", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "fruit", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "paintedmetal", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "default", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID33619( var_5, "none", var_0, "h1r_default_helicopter_wind" );
        _ID42400::_ID43764( var_5, var_0, "fx/treadfx/heli_snow_default_landing" );
    }

    _ID42400::_ID33619( "script_vehicle_littlebird_player", "brick", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "bark", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "carpet", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "cloth", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "concrete", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "dirt", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "flesh", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "foliage", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "glass", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "grass", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "gravel", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "ice", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "metal", undefined, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "mud", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "paper", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "plaster", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "rock", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "sand", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "snow", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "slush", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "water", var_1, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "water_waist", var_1, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "wood", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "asphalt", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "ceramic", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "plastic", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "rubber", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "cushion", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "fruit", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "paintedmetal", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "default", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_littlebird_player", "none", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID43764( "script_vehicle_littlebird_player", var_0, "fx/treadfx/heli_snow_default_landing" );
    _ID42400::_ID33619( "pavelow", "brick", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "bark", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "carpet", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "cloth", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "concrete", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "dirt", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "flesh", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "foliage", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "glass", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "grass", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "gravel", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "ice", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "metal", undefined, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "mud", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "paper", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "plaster", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "rock", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "sand", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "snow", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "slush", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "water", var_1, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "water_waist", var_1, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "wood", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "asphalt", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "ceramic", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "plastic", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "rubber", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "cushion", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "fruit", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "paintedmetal", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "default", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "pavelow", "none", var_0, "h1r_default_helicopter_wind" );
    _ID42400::_ID33619( "script_vehicle_f15", "brick", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "bark", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "carpet", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "cloth", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "concrete", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "dirt", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "flesh", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "foliage", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "glass", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "grass", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "gravel", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "ice", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "metal", undefined );
    _ID42400::_ID33619( "script_vehicle_f15", "mud", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "paper", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "plaster", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "rock", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "sand", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "snow", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "slush", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "water", var_2 );
    _ID42400::_ID33619( "script_vehicle_f15", "water_waist", var_2 );
    _ID42400::_ID33619( "script_vehicle_f15", "wood", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "asphalt", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "ceramic", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "plastic", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "rubber", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "cushion", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "fruit", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "paintedmetal", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "default", var_0 );
    _ID42400::_ID33619( "script_vehicle_f15", "none", var_0 );
    level._ID48791 = 80;
    level._ID48115 = 400;
    level._ID46634 = 400;
    _ID42400::_ID52441( var_1 );
    _ID42400::_ID52441( "fx/treadfx/heli_snow_default_landing" );
    _ID42400::_ID52441( var_2 );
}

_ID45832()
{
    _ID42299::_ID49604( "light_orange_steady_FX_origin", "vfx/lights/emergency_light_gulag", undefined, "emergency_light_gulag" );
    _ID42231::_ID48620( "toy_propane_tank02", "fx/explosions/propane_large_exp_h2", "fx/explosions/propane_large_exp_h2_gulag" );
    _ID42299::_ID49604( "light_red_steady_FX_origin", "fx/misc/tower_light_red_steady_gulag", -2 );
}

_ID49799()
{
    var_0 = randomfloatrange( -25, -15 );
    _ID42299::_ID53720( "barrel_fire_gulag_FX_origin", "fx/fire/firelp_barrel_pm_gulag", var_0, "barrel_fire_gulag", "fire_barrel_small" );
    _ID42299::_ID53720( "cs_utility_light_FX_origin", "vfx/lights/light_utility_gulag", var_0, "utility_light_gulag" );
}
